# yamllint disable-file
# Answer file maintained by Copier for: https://github.com/KyleKing/calcipy_template
# Check into version control. Edit by re-running copier and changing responses to the questions
_commit: 0.13.3
_src_path: gh:KyleKing/calcipy_template
author_email: dev.act.kyle@gmail.com
author_name: Player1
author_username: kyleking
cname: game.kyleking.me
copyright_date: '2022'
development_branch: main
doc_dir: docs
include_adrs: false
install_extras: null
minimum_python: 3.10.5
package_name_py: game
project_description: Student/player implementation of the design_patterns_island game!
project_name: game
repository_namespace: DesignPatternsAdventure
repository_provider: https://github.com

