---
name: CI Pipeline

# FYI: Note that the tasks are prefixed with "_" to use the private versions

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - game/**
      - tests/**
      - pyproject.toml

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.10.5]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}

      - name: Run linters
        run: poetry run doit run --continue _check

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.10.5]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          os: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}

      #   # Based on: https://github.com/pyglet/pyglet/blob/3d7c3fe05a051905770012cd3e78e7bd4aec49ff/.github/workflows/unittests.yml#L62-L66
      # - if: contains(matrix.os, 'windows')
      #   name: Configure OpenGL on Windows
      #   uses: msys2/setup-msys2@v2
      #   with:
      #     msystem: MINGW64
      #     release: false
      #     install: mingw-w64-x86_64-mesa

      # TODO: Fix OpenGL error in Windows CI
      - if: ${{ !contains(matrix.os, 'windows') }}
        name: Test with pytest
        # poetry run doit run _test
        run: |-
          poetry run doit run test

  # check_types:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]
  #       python-version: [3.10.5]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/setup
  #       with:
  #         os: ${{ matrix.os }}
  #         python-version: ${{ matrix.python-version }}

  #     - name: Run linters
  #       run: poetry run doit run _check_types
